name: Build and publish

on:
  push:
    branches:
      - master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Manage npm modules cache
              uses: actions/cache@v1
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            
            - name: Use Java 15.x
              uses: actions/setup-java@v1
              with:
                java-version: '15'
            
            - name: Frontend - Install dependencies
              working-directory: frontend
              run: npm install

            - name: Frontend - Tests
              working-directory: frontend
              run: npm run test:ci

            - name: Frontend - Build and copy to backend
              working-directory: frontend
              run: npm run build

            - name: Backend - Tests
              working-directory: backend
              run: ./mvnw -B test
            
            - name: Backend - Build and package
              working-directory: backend
              run: ./mvnw -B package
              env:
                MAVEN_OPTS: --enable-preview
            
            - name: Backend - Build custom JVM
              working-directory: backend
              run: ./create-custom-jvm.sh
            
            - name: Desktop wrapper - Install dependencies
              working-directory: desktop-wrapper
              run: npm install
            
            - name: Desktop wrapper - Publish
              working-directory: desktop-wrapper
              run: npm run publish
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
            # - name: Compute checksum
            #   working-directory: desktop-wrapper
            #   run: |
            #     chmod +x ./compute-checksum.sh
            #     ./compute-checksum.sh
            
            # - name: Release
            #   uses: softprops/action-gh-release@v1
            #   with:
            #     files: |
            #       ./*.sha256
            #   env:
            #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
